// 가이드 · 사용자앱 화면목록 (IA)
// 최대 5개 컬럼(d1~d5). 시트에 6depth 이상이면 마지막 두 단계 문구를 d5 하나에 ' · '로 합침.
// IA 시트 동기화. 목록 NO는 1~87 연속(중복 번호는 뒤 행부터 +1 밀림).
var TABLE_DATE = {
  사용자앱: [
    {
      no: '1',
      id: 'MFC001',
      type: 'PAGE',
      d1: '메인',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC001.html',
      status: '완료',
      note: '헤더 로그인 전',
    },
    {
      no: '2',
      id: 'MFC002',
      type: 'PAGE',
      d1: '검색',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC002.html',
      status: '완료',
      note: ' ',
    },
    {
      no: '3',
      id: 'MFC002_01',
      type: 'PAGE',
      d1: '검색',
      d2: '검색결과',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC002_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '4',
      id: 'MFC003',
      type: 'PAGE',
      d1: 'FC 둘러보기',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC003.html',
      status: '완료',
      note: '',
    },
    {
      no: '5',
      id: 'MFC003_L01',
      type: 'POPUP',
      d1: 'FC 둘러보기',
      d2: '보험 선택',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC003.html',
      status: '완료',
      note: 'MFC003.html 내 팝업 포함',
    },
    {
      no: '6',
      id: 'MFC003_L02',
      type: 'POPUP',
      d1: 'FC 둘러보기',
      d2: '지역 선택',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC003.html',
      status: '완료',
      note: 'MFC003.html 내 팝업 포함',
    },
    {
      no: '7',
      id: 'MFC003_01',
      type: 'PAGE',
      d1: 'FC 둘러보기',
      d2: 'FC상세보기',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC003_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '8',
      id: 'MFC003_01_L01',
      type: 'POPUP',
      d1: 'FC 둘러보기',
      d2: 'FC상세보기',
      d3: '후기 상세',
      d4: '',
      d5: '',
      path: './html/MFC003_01_L01.html',
      status: '완료',
      note: '',
    },
    {
      no: '9',
      id: 'MFC003_01_L02',
      type: 'POPUP',
      d1: 'FC 둘러보기',
      d2: 'FC상세보기',
      d3: '활동 스토리 상세',
      d4: '',
      d5: '',
      path: './html/MFC003_01_L02.html',
      status: '완료',
      note: '',
    },
    {
      no: '10',
      id: 'MFC003_02',
      type: 'PAGE',
      d1: 'FC 둘러보기',
      d2: 'FC상세보기',
      d3: '상담 요청',
      d4: '',
      d5: '',
      path: './html/MFC003_02.html',
      status: '완료',
      note: '',
    },
    {
      no: '11',
      id: 'MFC003_02_L02',
      type: 'POPUP',
      d1: 'FC 둘러보기',
      d2: 'FC상세보기',
      d3: '상담 요청',
      d4: '상담 요청 확인',
      d5: '',
      path: './html/MFC003_02_L02.html',
      status: '완료',
      note: '',
    },
    {
      no: '12',
      id: 'MFC003_02_01',
      type: 'PAGE',
      d1: '',
      d2: '',
      d3: '',
      d4: '',
      d5: '상담 요청 완료',
      path: './html/MFC003_02_01.html',
      status: '완료',
      note: '',
    },

    {
      no: '13',
      id: 'MFC004_L01',
      type: 'POPUP',
      d1: '마이페이지(개인)',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC001.html',
      status: '완료',
      note: '상단 프로필 클릭시 팝업',
    },
    {
      no: '14',
      id: 'MFC004_L01_01',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '내 정보',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC004_L01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '15',
      id: 'MFC004_L01_01_01',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '내 정보',
      d3: '회원탈퇴',
      d4: '',
      d5: '',
      path: './html/MFC004_L01_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '16',
      id: 'MFC004_L01_01_02',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '내 정보',
      d3: '회원탈퇴',
      d4: '회원 탈퇴 완료',
      d5: '',
      path: './html/MFC004_L01_01_02.html',
      status: '완료',
      note: '',
    },
    {
      no: '17',
      id: 'MFC004_L01_02',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '내 증권 관리',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC004_L01_02.html',
      status: '완료',
      note: '',
    },
    {
      no: '18',
      id: 'MFC004_L01_03',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '내 관심 FC',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC004_L01_03.html',
      status: '완료',
      note: '',
    },
    {
      no: '19',
      id: 'MFC004_L01_04',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '상담 현황',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC004_L01_04.html',
      status: '완료',
      note: '',
    },
    {
      no: '20',
      id: 'MFC004_L01_04_01',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '상담 현황',
      d3: '후기 작성',
      d4: '',
      d5: '',
      path: './html/MFC004_L01_04_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '21',
      id: 'MFC004_L01_04_01_01',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '상담 현황',
      d3: '후기 작성',
      d4: '후기 작성 완료',
      d5: '',
      path: './html/MFC004_L01_04_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '22',
      id: 'MFC004_L01_05',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '나의 후기',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC004_L01_05.html',
      status: '완료',
      note: '',
    },
    {
      no: '23',
      id: 'MFC004_L01_05_01',
      type: 'PAGE',
      d1: '마이페이지(개인)',
      d2: '나의 후기',
      d3: '후기 상세',
      d4: '',
      d5: '',
      path: './html/MFC003_01_L01.html',
      status: '완료',
      note: 'MFC003_01_L01 중복',
    },
    {
      no: '24',
      id: 'MFC004_L01_06',
      type: 'POPUP',
      d1: '마이페이지(개인)',
      d2: '로그아웃',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC004_L01_06.html',
      status: '완료',
      note: '',
    },

    {
      no: '25',
      id: 'MFC005_L01',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC005_L01.html',
      status: '완료',
      note: '상단 프로필 클릭시 팝업',
    },
    {
      no: '26',
      id: 'MFC005_L01_01',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '프로필 관리',
      d3: '기본 정보 입력',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '27',
      id: 'MFC005_L01_01_01',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '프로필 관리',
      d3: '활동정보 입력',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_01_01.html',
      status: '완료',
      note: 'MFC008_03 기반',
    },
    {
      no: '28',
      id: 'MFC005_L01_01_02',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '프로필 관리',
      d3: '프로필 입력',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_01_02.html',
      status: '완료',
      note: 'MFC008_02 기반',
    },
    {
      no: '29',
      id: 'MFC005_L01_01_03',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '프로필 관리',
      d3: '활동 스토리',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_01_03.html',
      status: '완료',
      note: 'MFC008_04 기반',
    },
    {
      no: '30',
      id: 'MFC005_L01_01_04',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '프로필 관리',
      d3: '약관 및 동의',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_01_04.html',
      status: '완료',
      note: 'MFC008 기반',
    },
    {
      no: '31',
      id: 'MFC005_L01_01_05',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '프로필 관리',
      d3: '회원탈퇴',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_01_05.html',
      status: '완료',
      note: '',
    },
    {
      no: '32',
      id: 'MFC005_L01_01_06',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '프로필 관리',
      d3: '회원탈퇴',
      d4: '회원 탈퇴 완료',
      d5: '',
      path: './html/MFC004_L01_01_02.html',
      status: '완료',
      note: 'MFC004_L01_01_02 중복',
    },
    {
      no: '33',
      id: 'MFC005_L01_01_L06',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '프로필 관리',
      d3: '프로필 수정 완료',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_01_L06.html',
      status: '완료',
      note: '',
    },
    {
      no: '34',
      id: 'MFC005_L01_02',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '심의필 정보 관리',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_02.html',
      status: '완료',
      note: '',
    },
    {
      no: '35',
      id: 'MFC005_L01_02_L01',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '심의필 정보 관리',
      d3: '심의필 정보 등록 확인',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_02_L01.html',
      status: '완료',
      note: '',
    },
    {
      no: '36',
      id: 'MFC005_L01_02_L02',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '심의필 정보 관리',
      d3: '심의필 승인 거부 사유',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_02_L02.html',
      status: '완료',
      note: '',
    },
    {
      no: '37',
      id: 'MFC005_L01_03',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '상담 신청 관리',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_03.html',
      status: '완료',
      note: '',
    },
    {
      no: '38',
      id: 'MFC005_L01_03_01',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '상담 신청 관리',
      d3: '상담요청 상세',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_03_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '39',
      id: 'MFC005_L01_03_L02',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '상담 신청 관리',
      d3: '상담요청 상세',
      d4: '상담 거부 사유',
      d5: '',
      path: './html/MFC005_L01_03_L02.html',
      status: '완료',
      note: '입력',
    },
    {
      no: '40',
      id: 'MFC005_L01_03_L03',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '상담 신청 관리',
      d3: '상담요청 상세',
      d4: '상담 거부 사유 보기',
      d5: '',
      path: './html/MFC005_L01_03_L03.html',
      status: '완료',
      note: '',
    },
    {
      no: '41',
      id: 'MFC005_L01_04',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_04.html',
      status: '완료',
      note: '',
    },
    {
      no: '42',
      id: 'MFC005_L01_04_01',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '지역별',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_04_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '43',
      id: 'MFC005_L01_04_01_L01',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '지역별',
      d4: '지역 선택',
      d5: '',
      path: './html/MFC005_L01_04_01.html',
      status: '완료',
      note: 'MFC005_L01_04_01.html 내 팝업 포함',
    },
    {
      no: '44',
      id: 'MFC005_L01_04_01_01',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '지역별',
      d4: '',
      d5: '광고 신청 완료',
      path: './html/MFC005_L01_04_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '45',
      id: 'MFC005_L01_04_02',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '배너 광고',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_04_02.html',
      status: '완료',
      note: '',
    },
    {
      no: '46',
      id: 'MFC005_L01_04_02_L01',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '배너 광고',
      d4: '노출영역 보기',
      d5: '',
      path: './html/MFC005_L01_04_02_L01.html',
      status: '',
      note: '캡쳐 필요',
    },
    {
      no: '47',
      id: 'MFC005_L01_04_01_01',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '배너 광고',
      d4: '',
      d5: '광고 신청 완료',
      path: './html/MFC005_L01_04_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '48',
      id: 'MFC005_L01_04_03',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '보험상품별',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_04_03.html',
      status: '완료',
      note: '',
    },
    {
      no: '49',
      id: 'MFC005_L01_04_03_L01',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '보험상품별',
      d4: '보험 항목 선택',
      d5: '',
      path: './html/MFC005_L01_04_03.html',
      status: '완료',
      note: 'MFC005_L01_04_03.html 내 팝업 포함',
    },
    {
      no: '50',
      id: 'MFC005_L01_04_01_01',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '보험상품별',
      d4: '',
      d5: '광고 신청 완료',
      path: './html/MFC005_L01_04_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '51',
      id: 'MFC005_L01_04_04',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '후기 광고',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_04_04.html',
      status: '완료',
      note: '',
    },
    {
      no: '52',
      id: 'MFC005_L01_04_04_L01',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '후기 광고',
      d4: '후기 선택',
      d5: '',
      path: './html/MFC005_L01_04_04_L01.html',
      status: '완료',
      note: '',
    },
    {
      no: '53',
      id: 'MFC005_L01_04_01_01',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '후기 광고',
      d4: '',
      d5: '광고 신청 완료',
      path: './html/MFC005_L01_04_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '54',
      id: 'MFC005_L01_04_05',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '상담 언어별',
      d4: '',
      d5: '',
      path: './html/MFC005_L01_04_05.html',
      status: '완료',
      note: '',
    },
    {
      no: '55',
      id: 'MFC005_L01_04_05_L01',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '상담 언어별',
      d4: '언어 선택',
      d5: '',
      path: './html/MFC005_L01_04_05.html',
      status: '완료',
      note: 'MFC005_L01_04_05.html 내 팝업 포함',
    },
    {
      no: '56',
      id: 'MFC005_L01_04_01_01',
      type: 'PAGE',
      d1: '마이페이지(FC)',
      d2: '광고 관리',
      d3: '상담 언어별',
      d4: '',
      d5: '광고 신청 완료',
      path: './html/MFC005_L01_04_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '57',
      id: 'MFC005_L01_06',
      type: 'POPUP',
      d1: '마이페이지(FC)',
      d2: '로그아웃',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC004_L01_06.html',
      status: '완료',
      note: 'MFC004_L01_06.html 중복',
    },

    {
      no: '58',
      id: 'MFC006_01',
      type: 'PAGE',
      d1: '로그인',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC006_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '59',
      id: 'MFC006_01_01',
      type: 'PAGE',
      d1: '로그인',
      d2: '계정찾기',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC006_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '60',
      id: 'MFC006_01_01_01',
      type: 'PAGE',
      d1: '로그인',
      d2: '계정찾기',
      d3: '계정찾기 결과',
      d4: '',
      d5: '',
      path: './html/MFC006_01_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '61',
      id: 'MFC006_01_02',
      type: 'PAGE',
      d1: '로그인',
      d2: '비밀번호 재설정',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC006_01_02.html',
      status: '완료',
      note: '',
    },
    {
      no: '62',
      id: 'MFC006_01_02_01',
      type: 'PAGE',
      d1: '로그인',
      d2: '비밀번호 재설정',
      d3: '비밀번호 재설정 안내 메일',
      d4: '',
      d5: '',
      path: './html/MFC006_01_02_01.html',
      status: '',
      note: '',
    },
    {
      no: '63',
      id: 'MFC006_01_02_01_01',
      type: 'PAGE',
      d1: '로그인',
      d2: '비밀번호 재설정',
      d3: '비밀번호 재설정 안내 메일',
      d4: '비밀번호 입력',
      d5: '',
      path: './html/MFC006_01_02_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '64',
      id: 'MFC006_01_02_01_01_01',
      type: 'PAGE',
      d1: '로그인',
      d2: '비밀번호 재설정',
      d3: '비밀번호 재설정 안내 메일',
      d4: '비밀번호 입력',
      d5: '비밀번호 변경완료',
      path: './html/MFC006_01_02_01_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '65',
      id: 'MFC006_01_L03',
      type: 'POPUP',
      d1: '로그인',
      d2: '재심의 알림',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC006_01_L03.html',
      status: '완료',
      note: '',
    },
    {
      no: '66',
      id: 'MFC006_01_L04',
      type: 'POPUP',
      d1: '로그인',
      d2: '심의필 미등록 안내',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC006_01_L04.html',
      status: '완료',
      note: '',
    },
    {
      no: '66-1',
      id: 'MFC006_01_L05',
      type: 'POPUP',
      d1: '로그인',
      d2: '프로필 미등록 안내',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC006_01_L05.html',
      status: '완료',
      note: '',
    },

    {
      no: '67',
      id: 'MFC007',
      type: 'PAGE',
      d1: '회원가입',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC007_select.html',
      status: '완료',
      note: '',
    },
    {
      no: '68',
      id: 'MFC007_01',
      type: 'PAGE',
      d1: '회원가입',
      d2: '개인 회원가입',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC007.html',
      status: '완료',
      note: '',
    },
    {
      no: '69',
      id: 'MFC007_L01',
      type: 'POPUP',
      d1: '회원가입',
      d2: '개인 회원가입',
      d3: '이용약관',
      d4: '',
      d5: '',
      path: './html/MFC007_L01.html',
      status: '완료',
      note: '',
    },
    {
      no: '70',
      id: 'MFC007_L02',
      type: 'POPUP',
      d1: '회원가입',
      d2: '개인 회원가입',
      d3: '개인정보 수집 및 이용',
      d4: '',
      d5: '',
      path: './html/MFC007_L02.html',
      status: '완료',
      note: '',
    },
    {
      no: '71',
      id: 'MFC007_L03',
      type: 'POPUP',
      d1: '회원가입',
      d2: '개인 회원가입',
      d3: '마케팅 활용',
      d4: '',
      d5: '',
      path: './html/MFC007_L03.html',
      status: '완료',
      note: '',
    },
    {
      no: '72',
      id: 'MFC007_01_01',
      type: 'PAGE',
      d1: '회원가입',
      d2: '개인 회원가입',
      d3: '',
      d4: '회원가입완료',
      d5: '',
      path: './html/MFC007_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '73',
      id: 'MFC008',
      type: 'PAGE',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '약관 및 동의',
      d4: '',
      d5: '',
      path: './html/MFC008.html',
      status: '완료',
      note: '',
    },
    {
      no: '74',
      id: 'MFC008_01',
      type: 'PAGE',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '기본 정보 입력',
      d4: '',
      d5: '',
      path: './html/MFC008_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '75',
      id: 'MFC008_01_01',
      type: 'PAGE',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '기본 정보 입력',
      d4: '회원가입완료',
      d5: '',
      path: './html/MFC008_01_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '76',
      id: 'MFC008_02',
      type: 'PAGE',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '프로필 입력',
      d4: '',
      d5: '',
      path: './html/MFC008_02.html',
      status: '완료',
      note: '',
    },
    {
      no: '77',
      id: 'MFC008_02_L01',
      type: 'POPUP',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '프로필 입력',
      d4: '상담 가능 시간',
      d5: '',
      path: './html/MFC008_02.html',
      status: '완료',
      note: 'MFC008_02 내 팝업 포함',
    },
    {
      no: '78',
      id: 'MFC008_03',
      type: 'PAGE',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '활동 정보 입력',
      d4: '',
      d5: '',
      path: './html/MFC008_03.html',
      status: '완료',
      note: '',
    },
    {
      no: '79',
      id: 'MFC008_03_L01',
      type: 'POPUP',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '활동 정보 입력',
      d4: '본인 활동 지역',
      d5: '',
      path: './html/MFC008_03.html',
      status: '완료',
      note: 'MFC008_03 내 팝업 포함',
    },
    {
      no: '80',
      id: 'MFC008_03_L02',
      type: 'POPUP',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '활동 정보 입력',
      d4: '운영 가능 보험 항목',
      d5: '',
      path: './html/MFC008_03.html',
      status: '완료',
      note: 'MFC008_03 내 팝업 포함',
    },
    {
      no: '81',
      id: 'MFC008_04',
      type: 'PAGE',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '활동 스토리',
      d4: '',
      d5: '',
      path: './html/MFC008_04.html',
      status: '완료',
      note: '',
    },
    {
      no: '82',
      id: 'MFC008_L05',
      type: 'POPUP',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '심의필 절차 안내',
      d4: '',
      d5: '',
      path: './html/MFC008_L05.html',
      status: '완료',
      note: '',
    },
    {
      no: '83',
      id: 'MFC008_L05_L01',
      type: 'POPUP',
      d1: '회원가입',
      d2: 'FC 회원가입',
      d3: '심의필 절차 안내',
      d4: '심의 요청용 화면 미리보기',
      d5: '',
      path: './html/MFC008_L05_L01.html',
      status: '완료',
      note: '',
    },

    { no: '84', id: '외부Link', type: 'LINK', d1: '회사소개', d2: '', d3: '', d4: '', d5: '', path: '#', status: '', note: '외부 링크' },
    {
      no: '85',
      id: 'MFC009',
      type: 'PAGE',
      d1: '이용약관',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC009.html',
      status: '완료',
      note: '',
    },
    {
      no: '86',
      id: 'MFC010',
      type: 'PAGE',
      d1: '개인정보처리방침',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC010.html',
      status: '완료',
      note: '',
    },
    {
      no: '87',
      id: 'MFC011',
      type: 'PAGE',
      d1: '법적책임',
      d2: '',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC011.html',
      status: '완료',
      note: '',
    },
    {
      no: '88',
      id: 'MFC012',
      type: 'PAGE',
      d1: '보험IN',
      d2: 'Q&A 목록',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC012.html',
      status: '완료',
      note: '',
    },
    {
      no: '89',
      id: 'MFC012_01',
      type: 'PAGE',
      d1: '보험IN',
      d2: 'Q&A 상세',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC012_01.html',
      status: '완료',
      note: '',
    },
    {
      no: '90',
      id: 'MFC012_02',
      type: 'PAGE',
      d1: '보험IN',
      d2: '등록/수정',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC012_02.html',
      status: '완료',
      note: '',
    },
    {
      no: '91',
      id: 'MFC012_03',
      type: 'PAGE',
      d1: '보험IN',
      d2: '답변 등록(FC)',
      d3: '',
      d4: '',
      d5: '',
      path: './html/MFC012_03.html',
      status: '완료',
      note: '',
    },
  ],
};
